version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  groups:
    prod-dependancies:
      dependency-type: "production"
    dev-dependancies:
      dependency-type: "development"
    rails:
      patterns:
        - 'rails'
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
